### PR TITLE
Display Indicator if shuffle modifier card was drawn

### PR DESCRIPTION
**Pull request by Krizzzn**
The shuffle indicator is opaque until a reshuffle card is hit in the modifier deck. This helps to remember if a reshuffle is required at the end or not.

### CODE REVIEW

**Comment by Krizzzn** [comment]
Just saw that is addresses issue #51

**Comment by jacob-keller** [comment]
This looks good to me!

**Comment by GinoGalotti** [comment]
Looks good, was thinking about merging but... why did you kill the app.manifest? It helps us on Safari devices (I think, we got it really early on), as well as a way to force the cache version.

**Comment by Krizzzn** [comment]
Killing the file was actually an accident. I was always getting the cached version instead of the one with my changes. So I deleted it. Then I accidentally checked in the deletion. 
But I guess it’s anyways better if the file was only present in „production“/github-pages.

**Comment by GinoGalotti** [comment]
Fair enough, I am a lazy boy so I usually just push master to gh-pages when it's stable enough... ;p so I keep the cache there. But I'll squash it in

**Pull request merged**
