### PR TITLE
Improved flame demon

### PR DESCRIPTION
**Pull request by g1ul10**
I fixed the indentation in a couple of cards in which the flame demon is supposed to consume an element. I did it by using an HTML table. Maybe someone else can find a better solution. I'm rather satisfied by the result. The present version cards are nearer to the original and I think they are more clear too.

### CODE REVIEW

**Comment by GinoGalotti** [comment]
I'll spend some time tomorrow reviewing this and checking how it looks on Safari/etc.

But... can you rebase on top of Master again? It shows like a lot of commits, but you're only pushing 1. Ideally, the merge that you did with master, it's better if you just rebase it. 

Or, even better, you can just checkout the latest master, make your change, and push. That way, it'll show 1 commit to merge... instead of 10 for a 1-line change :p

**Comment by g1ul10** [comment]
Sure. I'll do it. Sorry for the troubles.

**Comment by GinoGalotti** [comment]
Oh, no troubles at all! Just sharing with you some guidelines.

It looks really good on Chrome and Safari. Will merge this tomorrow, in case you want to rebase or change the commit history. Thanks for helping!

**Comment by g1ul10** [comment]
I tried for a couple of hours to do what you suggested but I failed. The whole logic of this collaborative system escapes me. I feel frustrated and angry (and old). As far as I can tell, all my branches differ for just two lines from johreh/master...

How can I just re-sync my fork with the original and forget about what happened before? A clean start, so to speak? I don't pretend that you have time to explain github to me, but I have a couple of other suggestions of possible improvements I'd like to share and I want to do it in the way that is more convenient to you (and everybody else here). If it sounds as a desperate request for help... it's because this is exactly what it is :-)

**Comment by GinoGalotti** [comment]
Yes, you can. If you give up, the easiest solution is:
`git checkout upstream/master` (if you have configured upstream as johreh's repo, steps: https://help.github.com/articles/syncing-a-fork/ ) 
That way you have a clean upstream.
Do the changes of your 2 lines. Commit them in a simple commit.
Now: You can either create a new branch, close this pull request and open a new one.
Or you can overwrite this branch with the new work.

For the later, just do:
`git push -f origin HEAD:improved_flame_demo`. 
It is telling GitHub that you want to force an overwrite on the head of your branch with the working copy. 

If you don't want to deal with this, I'll just squash all your commits tomorrow and merge that. :) It was just in case you wanted to make it shine yourself!

Thanks for collaborating!

**Pull request closed without merging**
