### PR TITLE
Added several enemies and changed macros to support them

### PR DESCRIPTION
**Pull request by GinoGalotti**
If this gets green light, I'll add more enemies
TODO: Don't know how to horizontally flip an image from HTML, so Pull has a wrong icon

### CODE REVIEW

**Comment by ervwalter** [comment]
Here is an edited version of the push SVG file with the arrow flipped the other way that you could use without needing the CSS transform:

https://www.dropbox.com/s/36jnmdluga8p0r1/pull.svg?dl=0

**Comment by GinoGalotti** [comment]
Thanks for the file, but does it make sense? It is just a flipped image. I assumed that for that doing that kind of transforms were better on the go (that's why we have the Macros for).

There is a similar issue with all the elemental symbols and the "forbidden" overlay, shall I create images with both at the same time? Or just dynamically combine them?

Will wait for johreh. Don't mind using the new image, but just in case!

**Comment by ervwalter** [comment]
I think your original commit was fine, but your code comment was that you felt it was "ugly" and you were looking for an alternative solution.  A dedicated separate file is pretty much the only other solution I can think of.  I personally would stick with the CSS solution.

**Comment by johreh** [comment]
Great work!

Solution for consume element is on the way and will be up in a moment. I have an idea for AoE icons too, but its gonna take a while to solve that.

**Pull request merged**
