### PR TITLE
Fixing animation glitches on Safari on Mac and iOS

### PR DESCRIPTION
**Pull request by Krizzzn**
The card flip animation glitches on safari on mac and mobile. This fixes the problem.

### CODE REVIEW

**Comment by nickv2002** [comment]
If @johreh doesn't accept this commit you can try pushing to this fork that has been updating instead:

https://github.com/g1ul10/gloomycompanion

**Comment by Krizzzn** [comment]
Opened the PR with @g1ul10's fork. By the way: I try to keep mine up to date as well: https://krizzzn.github.io/gloomycompanion/

I pulled in almost all card.js updates I could find on github.

**Comment by nickv2002** [comment]
Thanks @Krizzzn 

Maybe you and @g1ul10 can work together to keep 1 updated copy instead of worrying about which one is most up to date.

**Comment by GinoGalotti** [comment]
Don't have Safari myself, but I played a little bit with it on my Chrome and nothing seemed to break. Couldn't spend a lot of time,tho; and I've recently merged 3-4 commits so... please, take a look again! Thanks or contributing :)

**Comment by stellentus** [comment]
Is this active at johreh.github.io/gloomycompanion yet? The animation is still weird on Safari.

**Comment by Krizzzn** [comment]
It is live. It might be that your browser still uses the cached version, because it did not pick up the cache manifest changes.  
Look at the ability decks: if they don’t show monster health, the version is from the cache. 
Try the private mode of Safari or append ?cache=23342 to the url. 
(BTW: the fix only is for the card flip animation not for the turn animation. I couldn’t find a solution for the turn, but the flip happens more often so i thought it was worth to open a PR)

**Pull request merged**
