### PR TITLE
#54: curse and bless cards capped at ten

### PR DESCRIPTION
**Pull request by AndClarke**

### CODE REVIEW

**Comment by GinoGalotti** [comment]
Do we know if this is a "real" rule? I remember reading a lot of discussions months ago of techniques to clutter the monster deck with curses. Can't recall if there are only 10 curse cards in the deck... any source or something? thanks!

**Comment by GinoGalotti** [comment]
I mean... it seems like there is not a hardcoded rule... :( maybe it was a limitation on the number of cards he wanted to print. Ideally, I would love to see this as options on the web, so people can choose to play "as close as possible" to the board game, or get rid of those physical limitations. I'll merge it in, tho.

**Comment by stellentus** [comment]
The rules intentionally limit it to 10 cards, even though there are actually 20 curse cards available:
Rule book, page 23:
> Note that there are two separate curse decks: 10 cards with a `(m)` in the lower left corner and 10 cards with an `(*)`. `(m)` cards can only be placed in the monster attack deck (when a monster is cursed), and `(*)` cards can only be placed in a character's attack deck (when a character or character summon is cursed). Thus, a maximum of only 10 curse cards can be placed into any one deck.

But I agree some people might like the option to disable the limit.

**Comment by GinoGalotti** [comment]
I remember being in some discussions, so maybe that rule was added for V2? It makes total sense, and now the app uses it!

**Pull request merged**
