### PR TITLE
Updated monster cards per second edition change log

### PR DESCRIPTION
**Pull request by sanjayvsingh**
Based on the [second edition change log](https://boardgamegeek.com/thread/1761512/official-second-printing-change-log), this updates the following cards:

Line 202 - Card 679
Line 300 - Card 713
Lines 333, 334 - Cards 590, 591

The other monster ability cards and stats seem to already be working fine, so I left those alone.

### CODE REVIEW

**Comment by sanjayvsingh** [comment]
@g1ul10 Any chance you can review this before the weekend? That's our next session and it would be great to run this from the website instead of a local copy. Thanks.

**Comment by g1ul10** [comment]
There's a misunderstanding here. I don't have any rule on the project here. Gino Gallotti is responsible. But you can use your own version from your github account. In any case I will consider to add your modifications to my version for sure. You can reach it using "g1ul10" instead of "johreh".

**Comment by sanjayvsingh** [comment]
@g1ul10 , thank you. Sorry for the misunderstanding.

**Comment by GinoGalotti** [comment]
Sorry, I lost the 2FactorAuth and never got any notification from this. This change has already been merged in https://github.com/johreh/gloomycompanion/commit/f9e0c0ea3d7954cf8516f60ae785839554d4d264 . Please, feel free to check the latest version and say if there's anything missing!

**Pull request closed without merging**
