### PR TITLE
Added range spec to all ranged attack

### PR DESCRIPTION
**Pull request by g1ul10**
I've added %range +0 to all attacks of ranged monsters that do not modify the range. In this way the range of the attack can be directly read from the card without need of checking the stat card of the monster.

### CODE REVIEW

**Comment by GinoGalotti** [comment]
Wow, didn't realise that we were already dealing with range, so it was just about adding the text to every attack.

The flying icon is broken in your version, tho. Will try to get the changes locally. https://g1ul10.github.io/gloomycompanion/?change . Maybe I forgot to include the image on master

**Comment by GinoGalotti** [comment]
@g1ul10 
Using the regex `(%attack%)(.)*(%range%)` you can highlight the lines where you have attack and range. Checking things, I've found that the following are missing range (I don't have the rules on my own, so I don't know if they should have it)

Boss:
            , [false, "36", "* %move% +0", "* %attack% +0"]

Imp 
            , [false, "42", "* %move% +1", "* %heal% 2"]
(Although, IIRC, I think all the heals who doesn't have a range, its range should be 3 as specified by the version 2 changes)

Wind Demon:
            , [false, "37", "* %move% +0", "* %attack% +0 <div style='display: inline-block; width: 0; margin-top: -1.5em; vertical-align: bottom'>%aoe-4-with-black%</div>", "** %air%%use_element%: +1 Attack <div style='display: inline-block; margin-right: -3em'>%aoe-circle-with-side-black%</div>"]
(The first part should have range, I assume)

**Comment by g1ul10** [comment]
The heal range on the Imp card is actually omitted. This is due do change in the second printing but I'd rather prepare a specific pull request about an "updating" of the cards to the second printing. The attack of the wind demon is a melee attack. So it is correct as it is now. Concerning the boss, that's difficult. Not all bosses have a range. So if we insert a a "$range +0" spec we will see a "range 0" on the card which is ugly.

**Comment by g1ul10** [comment]
I actually found that the "fly.svg" icon, which for some reason I did not see before, is better then the "flying.svg" icon so I suggest to use the former.

**Comment by GinoGalotti** [comment]
Looks pretty enough to me! Thanks for helping! Merging and updating gh-pages as well.

**Pull request merged**
