### PR TITLE
cards.js updates

### PR DESCRIPTION
**Pull request by sfrazer**
Reorganized to make the list alphabetical. Added a blank template at top as comment.

Finished monsters through Harrower Infester so far.

Need the following macros:

%wound% macro
%pierce% macro
%jump% macro

Produce and use macros for the elements:

%fire%
%ice%
%air%
%earth%
%light%
%dark%
%use-fire%
%use-ice%
%use-air%
%use-earth%
%use-light%
%use-dark%
%use-any%

Also need a method to show area effects.

### CODE REVIEW

**Comment by sfrazer** [comment]
(Still new to github, apologies for the multiple changes)

Updated to use new element usage

**Comment by sfrazer** [comment]
This is the last of the enemies. I merged in (by hand) the enemies Gino did.

Assuming the element names are all correct, the only changes this file will need is the Area Effect stuff.

**Comment by sfrazer** [comment]
And here's the full scenario list. Number 55 is missing because it relies on random monster pulls.

I think that's about all I can help with. Hope this is worthwhile.

**Comment by GinoGalotti** [comment]
Wow that's a lot of work!
Regarding merges.... please, don't do merges by hand! Git manage merges with ease, and actually after pushing anything to master, you should merge with the latest master before!
Last piece of advice: if one of the changes is a reformat or just reordering things, for the sake of the reviewers it is recommended to push it on a following Pull Request. That way they can review the change, and then review the reordering.. otherwise, it can be really messy! (with the size of this repo, it won't be a real problem)
I like the solution for the use element, johreh was working on another one as well, hopefully we can mix them!
And thanks for making the tool even cooler

**Comment by sfrazer** [comment]
Thanks,

Sorry for the merge stuff. Hopefully it's not too complicated. I've been trying to get the %use_element% to work, but I can't seem to get it to show up on top of the element icon. 

I also tried this in Safari in case it was a problem with Chrome. Safari didn't change the element icon behavior but the cards themselves looked terrible. After you click one, half the card remains behind.

Seems to happen on iOS as well.

**Comment by GinoGalotti** [comment]
Ok, then, my advice is:
Keep working on the use_element stuff. The owner is also working on that, maybe together we might reach a nice solution.
Create another Pull Request containing the changes that are tested and working (for instance, the Scenario list). Check that it works, put it alone. I highly recommend you working on branches, so you can work on all this features in parallel and create different Pull Request.
The Request reordering all the monsters I assume is tied to the first point... without a working use_element, it's not possible to merge the PR with master. Master will be broken! 

:) That's what I would be asked to do at work. It's a pretty common Git workflow! That way, it'll be really fast to accept and merge your Scenario list, without dealing with the rest of the things that you're not sure that they'll work!

**Comment by sfrazer** [comment]
I think I get it. I'll close this and submit separate pull requests.

**Pull request closed without merging**
